### PR TITLE
ARM support

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by bdpayne** [comment]
retest this please

**Comment by bdpayne** [comment]
retest this please

**Comment by bdpayne** [comment]
I believe the PR tester is now working properly with the ARM image.  However, I'm seeing a failure in the PR builder.  Perhaps there's a legit problem with this PR?

test_translate.c:77:F:LibVMI Translate:test_libvmi_piddtb:0: pid_to_dtb failed

**Comment by tklengyel** [comment]
I don't think pid_to_dtb ever worked for linux memory dumps. To be fair, linux memory dump support is relatively new to LibVMI and I don't think we ever really had it officially supported =)

So the issue is driver_get_address_width is not implemented for file mode. I'm just going to add heuristics around this in case we are in file mode to try bit 32-bit and 64-bit widths.

**Pull request closed without merging**
